const Router = require('koa-router');
const getClasses = require('../controller/getClassController');
const del = require('../controller/deleteUserController');
const addUser = require('../controller/addUserController');
const login = require('../controller/loginController');
const check = require('../controller/checkLoginController');
const readfile = require('../controller/readfileController');
const getId = require('../controller/getStudentController');
const modify = require('../controller/modifyPassController');
const unvalidate = require('../controller/getUnvalidateController');
const validate = require('../controller/validateController');
const checkT = require('../controller/checkTeacherController');
const setTime = require('../controller/timeController');
const request = require('../controller/requestContoller');
const excel = require('../controller/excelController');
const getRecord = require('../controller/getRecordsController');
const needReq = require('../controller/unnormalPunchController');
const addReq = require('../controller/addRequestController');
const conclude = require('../controller/concludeController');
const vacation = require('../controller/vacationController');
const kill = require('../controller/killRecordsController');

const router = new Router();
router.get('/getClasses', getClasses);
router.get('/add', addUser);
router.get('/login', login);
router.get('/check', check);
router.get('/readfile', readfile);
router.get('/getId', getId);
router.get('/modify', modify);
router.get('/unvalidate', unvalidate);
router.get('/validate', validate);
router.get('/checkT', checkT);
router.get('/del', del);
router.get('/setTime', setTime);
router.get('/getRequests', request.getRequest);
router.get('/allowReq', request.allowReq);
router.get('/deleteReq', request.deleteRequest);
router.get('/excel', excel);
router.get('/getRecord', getRecord);
router.get('/needReq', needReq);
router.get('/addReq', addReq);
router.get('/conclude', conclude);
router.get('/vacation', vacation);
router.get('/kill', kill);
module.exports = router;